name: npd

volumes:
  postgres_data:

services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    environment:
      POSTGRES_DB: npd_test

  db-migrations:
    extends:
      file: docker-compose.yml
      service: db-migrations
    environment:
      FLYWAY_URL: jdbc:postgresql://${NPD_DB_HOST:-db}:${NPD_DB_PORT:-5432}/npd_test

  django-web:
    extends:
      file: docker-compose.yml
      service: django-web
    environment:
      NPD_DB_NAME: npd_test