name: npd

volumes:
  postgres_data:

services:
  db:
    extends:
      file: docker-compose.yml
      service: db
    environment:
      POSTGRES_DB: npd_test

  db-migrations:
    extends:
      file: docker-compose.yml
      service: db-migrations
    environment:
      FLYWAY_URL: jdbc:postgresql://${NPD_DB_HOST:-db}:${NPD_DB_PORT:-5432}/npd_test
    volumes: !override
      - '../flyway/sql/django_migrations:/flyway/sql/django_migrations'
      - '../flyway/sql/django_reference_data:/flyway/sql/django_reference_data'
      - '../flyway/sql/migrations:/flyway/sql/migrations'
      - '../flyway/sql/reference_data:/flyway/sql/reference_data'



  django-web:
    extends:
      file: docker-compose.yml
      service: django-web
    environment:
      NPD_DB_NAME: npd_test