# service: 
#   image: or build:
#   env_file: 
#   environment:
#   ports:
#   volumes:
#   networks:
#   depends_on:
#   command:

services:
  db:
    image: 'postgres:17'
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${NPD_DB_NAME}
      POSTGRES_USER: ${NPD_DB_USER}
      POSTGRES_PASSWORD: ${NPD_DB_PASSWORD}
    ports:
      - '${NPD_DB_PORT}:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - npd

  db-migrations:
    image: 'flyway/flyway:10'
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://${NPD_DB_HOST}:5432/${NPD_DB_NAME}
      FLYWAY_USER: ${NPD_DB_USER}
      FLYWAY_PASSWORD: ${NPD_DB_PASSWORD}
    volumes:
      - '../flyway/sql:/flyway/sql'
    networks:
      - npd
    depends_on: 
      - db
    command: migrate -environment=development 

  django-web:
    build: .
    container_name: npd
    env_file:
      - .env
    environment:
      NPD_DJANGO_SECRET: ${NPD_DJANGO_SECRET}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${NPD_DB_ENGINE}
      NPD_DB_NAME: ${NPD_DB_NAME}
      NPD_DB_USER: ${NPD_DB_USER}
      NPD_DB_PASSWORD: ${NPD_DB_PASSWORD}
      NPD_DB_HOST: ${NPD_DB_HOST}
      NPD_DB_PORT: 5432
    ports:
      - '8000:8000'
    volumes:
      - '.:/app'
      - ./artifacts:/artifacts
    networks:
      - npd
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  npd:
