services:
  db-test:
    image: postgres:17
    container_name: npd_db_test
    environment:
      POSTGRES_DB: test_${NPD_DB_NAME}
      POSTGRES_USER: ${NPD_DB_USER}
      POSTGRES_PASSWORD: ${NPD_DB_PASSWORD}
    ports:
      - "${NPD_DB_PORT}:5432"
    networks:
      - npd
    tmpfs:
      - /var/lib/postgresql/data:rw,size=200m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${NPD_DB_USER} -d test_${NPD_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
  db-migrations:
    image: flyway/flyway:10
    command: -connectRetries=10 migrate
    volumes:
      - ../flyway/sql:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://db-test:5432/test_${NPD_DB_NAME}
      FLYWAY_USER: ${NPD_DB_USER}
      FLYWAY_PASSWORD: ${NPD_DB_PASSWORD}
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - npd
  sample-data-test:
    image: postgres:17
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    command: >
      bash -c "psql -h db-test -U ${NPD_DB_USER} -d test_${NPD_DB_NAME} -f /flyway/sql/inserts/R__sample_data.sql"
    environment:
      PGPASSWORD: ${NPD_DB_PASSWORD}
    volumes:
      - ../flyway/sql:/flyway/sql
    networks:
      - npd
networks:
  npd: