--
-- PostgreSQL database dump
--
-- Generated by running:
--   docker compose run --rm django-web python manage.py migrate --fake
--   docker compose run --rm -e PGPASSWORD=postgres db pg_dump -U postgres -h db -d npd_development -t npd.django_migrations
--
-- Name: django_migrations; Type: TABLE; Schema: npd; Owner: postgres
--
CREATE TABLE IF NOT EXISTS
    ${apiSchema}.django_migrations (
        id SERIAL PRIMARY KEY,
        app character varying(255) NOT NULL,
        name character varying(255) NOT NULL,
        applied timestamp with time zone NOT NULL
    );

INSERT INTO
    ${apiSchema}.django_migrations (app, name, applied)
VALUES
    ('contenttypes', '0001_initial', now()),
    ('auth', '0001_initial', now()),
    ('admin', '0001_initial', now()),
    ('admin', '0002_logentry_remove_auto_add', now()),
    (
        'admin',
        '0003_logentry_add_action_flag_choices',
        now()
    ),
    (
        'contenttypes',
        '0002_remove_content_type_name',
        now()
    ),
    (
        'auth',
        '0002_alter_permission_name_max_length',
        now()
    ),
    ('auth', '0003_alter_user_email_max_length', now()),
    ('auth', '0004_alter_user_username_opts', now()),
    ('auth', '0005_alter_user_last_login_null', now()),
    ('auth', '0006_require_contenttypes_0002', now()),
    (
        'auth',
        '0007_alter_validators_add_error_messages',
        now()
    ),
    (
        'auth',
        '0008_alter_user_username_max_length',
        now()
    ),
    (
        'auth',
        '0009_alter_user_last_name_max_length',
        now()
    ),
    ('auth', '0010_alter_group_name_max_length', now()),
    ('auth', '0011_update_proxy_permissions', now()),
    (
        'auth',
        '0012_alter_user_first_name_max_length',
        now()
    ),
    ('sessions', '0001_initial', now());