--
-- Create model FlagState
--
CREATE TABLE
    "flags_flagstate" (
        "id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "name" varchar(64) NOT NULL,
        "condition" varchar(64) NOT NULL,
        "value" varchar(127) NOT NULL
    );

--
-- Alter unique_together for flagstate (1 constraint(s))
--
ALTER TABLE "flags_flagstate"
ADD CONSTRAINT "flags_flagstate_name_condition_value_4e81ec48_uniq" UNIQUE ("name", "condition", "value");