/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null
/**
 * The name of the city, town, suburb, village or other community or delivery center.
 */
export type NameOfCityTownEtc = string | null
/**
 * Country - a nation as commonly understood or generally accepted.
 */
export type CountryEGCanBeISO31662Or3LetterCode = string | null
/**
 * The name of the administrative area (county).
 */
export type DistrictNameAkaCounty = string | null
/**
 * This component contains the house number, apartment number, street name, street direction,  P.O. Box number, delivery hints, and similar address information.
 */
export type StreetNameNumberDirectionPOBoxEtc = (string | null)[] | null
export type ExtensionFieldForLine = unknown[] | null
/**
 * A postal code designating a region defined by the postal service.
 */
export type PostalCodeForArea = string | null
/**
 * Sub-unit of a country with limited sovereignty in a federally organized country. A code may be used if codes are in common use (e.g. US 2 letter state codes).
 */
export type SubUnitOfCountryAbbreviationsOk = string | null
/**
 * Specifies the entire address as it should be displayed e.g. on a postal label. This may be provided instead of or as well as the specific parts.
 */
export type TextRepresentationOfTheAddress = string | null
/**
 * Distinguishes between physical addresses (those you can visit) and mailing addresses (e.g. PO Boxes and care-of addresses). Most addresses are both.
 */
export type PostalPhysicalBoth = string | null
/**
 * The purpose of this address.
 */
export type HomeWorkTempOldBillingPurposeOfThisAddress = string | null

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * An address expressed using postal conventions (as opposed to GPS or other
 * location definition formats).
 * An address expressed using postal conventions (as opposed to GPS or other
 * location definition formats).  This data type may be used to convey
 * addresses for use in delivering mail as well as for visiting locations
 * which might not be valid for mail delivery.  There are a variety of postal
 * address formats defined around the world.
 */
export interface Address {
  fhir_comments?: FhirComments
  extension?: AdditionalContentDefinedByImplementations
  id?: UniqueIdForInterElementReferencing
  city?: NameOfCityTownEtc
  _city?: unknown
  country?: CountryEGCanBeISO31662Or3LetterCode
  _country?: unknown
  district?: DistrictNameAkaCounty
  _district?: unknown
  line?: StreetNameNumberDirectionPOBoxEtc
  _line?: ExtensionFieldForLine
  period?: unknown
  postalCode?: PostalCodeForArea
  _postalCode?: unknown
  state?: SubUnitOfCountryAbbreviationsOk
  _state?: unknown
  text?: TextRepresentationOfTheAddress
  _text?: unknown
  type?: PostalPhysicalBoth
  _type?: unknown
  use?: HomeWorkTempOldBillingPurposeOfThisAddress
  _use?: unknown
}
