/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null;
/**
 * A reference to a code defined by a terminology system.
 */
export type CodeDefinedByATerminologySystem = unknown[] | null;
/**
 * A human language representation of the concept as seen/selected/uttered by the user who entered the data and/or which represents the intended meaning of the user.
 */
export type PlainTextRepresentationOfTheConcept = string | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * Concept - reference to a terminology or just  text.
 * A concept that may be defined by a formal reference to a terminology or
 * ontology or may be provided by text.
 */
export interface CodeableConcept {
  fhir_comments?: FhirComments;
  extension?: AdditionalContentDefinedByImplementations;
  id?: UniqueIdForInterElementReferencing;
  coding?: CodeDefinedByATerminologySystem;
  text?: PlainTextRepresentationOfTheConcept;
  _text?: unknown;
}
