/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null;
/**
 * A symbol in syntax defined by the system. The symbol may be a predefined code or an expression in a syntax defined by the coding system (e.g. post-coordination).
 */
export type SymbolInSyntaxDefinedByTheSystem = string | null;
/**
 * A representation of the meaning of the code in the system, following the rules of the system.
 */
export type RepresentationDefinedByTheSystem = string | null;
/**
 * The identification of the code system that defines the meaning of the symbol in the code.
 */
export type IdentityOfTheTerminologySystem = string | null;
/**
 * Indicates that this coding was chosen by a user directly - e.g. off a pick list of available items (codes or displays).
 */
export type IfThisCodingWasChosenDirectlyByTheUser = boolean | null;
/**
 * The version of the code system which was used when choosing this code. Note that a well-maintained code system does not need the version reported, because the meaning of codes is consistent across versions. However this cannot consistently be assured, and when the meaning is not guaranteed to be consistent, the version SHOULD be exchanged.
 */
export type VersionOfTheSystemIfRelevant = string | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * A reference to a code defined by a terminology system.
 */
export interface Coding {
  fhir_comments?: FhirComments;
  extension?: AdditionalContentDefinedByImplementations;
  id?: UniqueIdForInterElementReferencing;
  code?: SymbolInSyntaxDefinedByTheSystem;
  _code?: unknown;
  display?: RepresentationDefinedByTheSystem;
  _display?: unknown;
  system?: IdentityOfTheTerminologySystem;
  _system?: unknown;
  userSelected?: IfThisCodingWasChosenDirectlyByTheUser;
  _userSelected?: unknown;
  version?: VersionOfTheSystemIfRelevant;
  _version?: unknown;
}
