/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null;
/**
 * Specifies a preferred order in which to use a set of contacts. ContactPoints with lower rank values are more preferred than those with higher rank values.
 */
export type SpecifyPreferredOrderOfUse1Highest = number | null;
/**
 * Telecommunications form for contact point - what communications system is required to make use of the contact.
 */
export type PhoneFaxEmailPagerUrlSmsOther = string | null;
/**
 * Identifies the purpose for the contact point.
 */
export type HomeWorkTempOldMobilePurposeOfThisContactPoint = string | null;
/**
 * The actual contact point details, in a form that is meaningful to the designated communication system (i.e. phone number or email address).
 */
export type TheActualContactPointDetails = string | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * Details of a Technology mediated contact point (phone, fax, email, etc.).
 * Details for all kinds of technology mediated contact points for a person or
 * organization, including telephone, email, etc.
 */
export interface ContactPoint {
  fhir_comments?: FhirComments;
  extension?: AdditionalContentDefinedByImplementations;
  id?: UniqueIdForInterElementReferencing;
  period?: unknown;
  rank?: SpecifyPreferredOrderOfUse1Highest;
  _rank?: unknown;
  system?: PhoneFaxEmailPagerUrlSmsOther;
  _system?: unknown;
  use?: HomeWorkTempOldMobilePurposeOfThisContactPoint;
  _use?: unknown;
  value?: TheActualContactPointDetails;
  _value?: unknown;
}
