/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null
/**
 * The part of a name that links to the genealogy. In some cultures (e.g. Eritrea) the family name of a son is the first name of his father.
 */
export type FamilyNameOftenCalledSurname = string | null
/**
 * Given name.
 */
export type GivenNamesNotAlwaysFirstIncludesMiddleNames =
  | (string | null)[]
  | null
export type ExtensionFieldForGiven = unknown[] | null
/**
 * Part of the name that is acquired as a title due to academic, legal, employment or nobility status, etc. and that appears at the start of the name.
 */
export type PartsThatComeBeforeTheName = (string | null)[] | null
export type ExtensionFieldForPrefix = unknown[] | null
/**
 * Part of the name that is acquired as a title due to academic, legal, employment or nobility status, etc. and that appears at the end of the name.
 */
export type PartsThatComeAfterTheName = (string | null)[] | null
export type ExtensionFieldForSuffix = unknown[] | null
/**
 * Specifies the entire name as it should be displayed e.g. on an application UI. This may be provided instead of or as well as the specific parts.
 */
export type TextRepresentationOfTheFullName = string | null
/**
 * Identifies the purpose for this name.
 */
export type UsualOfficialTempNicknameAnonymousOldMaiden = string | null

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * Name of a human - parts and usage.
 * A human's name with the ability to identify parts and usage.
 */
export interface HumanName {
  fhir_comments?: FhirComments
  extension?: AdditionalContentDefinedByImplementations
  id?: UniqueIdForInterElementReferencing
  family?: FamilyNameOftenCalledSurname
  _family?: unknown
  given?: GivenNamesNotAlwaysFirstIncludesMiddleNames
  _given?: ExtensionFieldForGiven
  period?: unknown
  prefix?: PartsThatComeBeforeTheName
  _prefix?: ExtensionFieldForPrefix
  suffix?: PartsThatComeAfterTheName
  _suffix?: ExtensionFieldForSuffix
  text?: TextRepresentationOfTheFullName
  _text?: unknown
  use?: UsualOfficialTempNicknameAnonymousOldMaiden
  _use?: unknown
}
