/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null
/**
 * Establishes the namespace for the value - that is, a URL that describes a set values that are unique.
 */
export type TheNamespaceForTheIdentifierValue = string | null
/**
 * The purpose of this identifier.
 */
export type UsualOfficialTempSecondaryOldIfKnown = string | null
/**
 * The portion of the identifier typically relevant to the user and which is unique within the context of the system.
 */
export type TheValueThatIsUnique = string | null

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * An identifier intended for computation.
 * An identifier - identifies some entity uniquely and unambiguously.
 * Typically this is used for business identifiers.
 */
export interface Identifier {
  fhir_comments?: FhirComments
  extension?: AdditionalContentDefinedByImplementations
  id?: UniqueIdForInterElementReferencing
  assigner?: unknown
  period?: unknown
  system?: TheNamespaceForTheIdentifierValue
  _system?: unknown
  type?: unknown
  use?: UsualOfficialTempSecondaryOldIfKnown
  _use?: unknown
  value?: TheValueThatIsUnique
  _value?: unknown
}
