/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null
/**
 * The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
 */
export type LogicalIdOfThisArtifact = string | null
/**
 * A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.
 */
export type ASetOfRulesUnderWhichThisContentWasCreated = string | null
/**
 * The base language in which the resource is written.
 */
export type LanguageOfTheResourceContent = string | null
/**
 * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.
 */
export type ContainedInlineResources = unknown[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and manageable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
 */
export type ExtensionsThatCannotBeIgnored = unknown[] | null
export type WhetherTheOrganizationSRecordIsStillInActiveUse = boolean | null
export type AListOfAlternateNamesThatTheOrganizationIsKnownAsOrWasKnownAsInThePast =
  (string | null)[] | null
export type ExtensionFieldForAlias = unknown[] | null
/**
 * The contact details of communication devices available relevant to the specific Organization. This can include addresses, phone numbers, fax numbers, mobile numbers, email addresses and web sites.
 */
export type OfficialContactDetailsForTheOrganization = unknown[] | null
/**
 * Description of the organization, which helps provide additional general context on the organization to ensure that the correct organization is selected.
 */
export type AdditionalDetailsAboutTheOrganizationThatCouldBeDisplayedAsFurtherInformationToIdentifyTheOrganizationBeyondItsName =
  string | null
export type TechnicalEndpointsProvidingAccessToServicesOperatedForTheOrganization =
  unknown[] | null
/**
 * Identifier for the organization that is used to identify the organization across multiple disparate systems.
 */
export type IdentifiesThisOrganizationAcrossMultipleSystems = unknown[] | null
/**
 * A name associated with the organization.
 */
export type NameUsedForTheOrganization = string | null
/**
 * The official certifications, accreditations, training, designations and licenses that authorize and/or otherwise endorse the provision of care by the organization.  For example, an approval to provide a type of services issued by a certifying body (such as the US Joint Commission) to an organization.
 */
export type QualificationsCertificationsAccreditationsLicensesTrainingEtcPertainingToTheProvisionOfCare =
  unknown[] | null
/**
 * The kind(s) of organization that this is.
 */
export type KindOfOrganization = unknown[] | null

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * A grouping of people or organizations with a common purpose.
 * A formally or informally recognized grouping of people or organizations
 * formed for the purpose of achieving some form of collective action.
 * Includes companies, institutions, corporations, departments, community
 * groups, healthcare practice groups, payer/insurer, etc.
 */
export interface Organization {
  fhir_comments?: FhirComments
  id?: LogicalIdOfThisArtifact
  implicitRules?: ASetOfRulesUnderWhichThisContentWasCreated
  _implicitRules?: unknown
  language?: LanguageOfTheResourceContent
  _language?: unknown
  meta?: unknown
  contained?: ContainedInlineResources
  extension?: AdditionalContentDefinedByImplementations
  modifierExtension?: ExtensionsThatCannotBeIgnored
  text?: unknown
  active?: WhetherTheOrganizationSRecordIsStillInActiveUse
  _active?: unknown
  alias?: AListOfAlternateNamesThatTheOrganizationIsKnownAsOrWasKnownAsInThePast
  _alias?: ExtensionFieldForAlias
  contact?: OfficialContactDetailsForTheOrganization
  description?: AdditionalDetailsAboutTheOrganizationThatCouldBeDisplayedAsFurtherInformationToIdentifyTheOrganizationBeyondItsName
  _description?: unknown
  endpoint?: TechnicalEndpointsProvidingAccessToServicesOperatedForTheOrganization
  identifier?: IdentifiesThisOrganizationAcrossMultipleSystems
  name?: NameUsedForTheOrganization
  _name?: unknown
  partOf?: unknown
  qualification?: QualificationsCertificationsAccreditationsLicensesTrainingEtcPertainingToTheProvisionOfCare
  type?: KindOfOrganization
}
