/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null;
/**
 * May be used to represent additional information that is not part of the basic definition of the element. To make the use of extensions safe and manageable, there is a strict set of governance  applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null;
/**
 * Unique id for the element within a resource (for internal references). This may be any string value that does not contain spaces.
 */
export type UniqueIdForInterElementReferencing = string | null;
/**
 * The end of the period. If the end of the period is missing, it means no end was known or planned at the time the instance was created. The start may be in the past, and the end date in the future, which means that period is expected/planned to end at that time.
 */
export type EndTimeWithInclusiveBoundaryIfNotOngoing = string | null;
/**
 * The start of the period. The boundary is inclusive.
 */
export type StartingTimeWithInclusiveBoundary = string | null;

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * Time range defined by start and end date/time.
 * A time period defined by a start and end date and optionally time.
 */
export interface Period {
  fhir_comments?: FhirComments;
  extension?: AdditionalContentDefinedByImplementations;
  id?: UniqueIdForInterElementReferencing;
  end?: EndTimeWithInclusiveBoundaryIfNotOngoing;
  _end?: unknown;
  start?: StartingTimeWithInclusiveBoundary;
  _start?: unknown;
}
