/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type FhirComments = string | string[] | null
/**
 * The logical id of the resource, as used in the URL for the resource. Once assigned, this value never changes.
 */
export type LogicalIdOfThisArtifact = string | null
/**
 * A reference to a set of rules that were followed when the resource was constructed, and which must be understood when processing the content. Often, this is a reference to an implementation guide that defines the special rules along with other profiles etc.
 */
export type ASetOfRulesUnderWhichThisContentWasCreated = string | null
/**
 * The base language in which the resource is written.
 */
export type LanguageOfTheResourceContent = string | null
/**
 * These resources do not have an independent existence apart from the resource that contains them - they cannot be identified independently, nor can they have their own independent transaction scope. This is allowed to be a Parameters resource if and only if it is referenced by a resource that provides context/meaning.
 */
export type ContainedInlineResources = unknown[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the resource. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer can define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension.
 */
export type AdditionalContentDefinedByImplementations = unknown[] | null
/**
 * May be used to represent additional information that is not part of the basic definition of the resource and that modifies the understanding of the element that contains it and/or the understanding of the containing element's descendants. Usually modifier elements provide negation or qualification. To make the use of extensions safe and managable, there is a strict set of governance applied to the definition and use of extensions. Though any implementer is allowed to define an extension, there is a set of requirements that SHALL be met as part of the definition of the extension. Applications processing a resource are required to check for modifier extensions.  Modifier extensions SHALL NOT change the meaning of any elements on Resource or DomainResource (including cannot change the meaning of modifierExtension itself).
 */
export type ExtensionsThatCannotBeIgnored = unknown[] | null
export type WhetherThisPractitionerSRecordIsInActiveUse = boolean | null
/**
 * Address(es) of the practitioner that are not role specific (typically home address).  Work addresses are not typically entered in this property as they are usually role dependent.
 */
export type AddressEsOfThePractitionerThatAreNotRoleSpecificTypicallyHomeAddress =
  unknown[] | null
/**
 * The date of birth for the practitioner.
 */
export type TheDateOnWhichThePractitionerWasBorn = string | null
/**
 * A language which may be used to communicate with the practitioner, often for correspondence/administrative purposes.  The `PractitionerRole.communication` property should be used for publishing the languages that a practitioner is able to communicate with patients (on a per Organization/Role basis).
 */
export type ALanguageWhichMayBeUsedToCommunicateWithThePractitioner =
  | unknown[]
  | null
export type IndicatesIfThePractitionerIsDeceasedOrNot = boolean | null
export type IndicatesIfThePractitionerIsDeceasedOrNot1 = string | null
/**
 * Administrative Gender - the gender that the person is considered to have for administration and record keeping purposes.
 */
export type MaleFemaleOtherUnknown = string | null
/**
 * An identifier that applies to this person in this role.
 */
export type AnIdentifierForThePersonAsThisAgent = unknown[] | null
export type TheNameSAssociatedWithThePractitioner = unknown[] | null
export type ImageOfThePerson = unknown[] | null
/**
 * The official qualifications, certifications, accreditations, training, licenses (and other types of educations/skills/capabilities) that authorize or otherwise pertain to the provision of care by the practitioner.  For example, a medical license issued by a medical board of licensure authorizing the practitioner to practice medicine within a certain locality.
 */
export type QualificationsCertificationsAccreditationsLicensesTrainingEtcPertainingToTheProvisionOfCare =
  unknown[] | null
/**
 * A contact detail for the practitioner, e.g. a telephone number or an email address.
 */
export type AContactDetailForThePractitionerThatApplyToAllRoles =
  | unknown[]
  | null

/**
 * Disclaimer: Any field name ends with ``__ext`` doesn't part of
 * Resource StructureDefinition, instead used to enable Extensibility feature
 * for FHIR Primitive Data Types.
 *
 * A person with a  formal responsibility in the provisioning of healthcare or
 * related services.
 * A person who is directly or indirectly involved in the provisioning of
 * healthcare or related services.
 */
export interface Practitioner {
  fhir_comments?: FhirComments
  id?: LogicalIdOfThisArtifact
  implicitRules?: ASetOfRulesUnderWhichThisContentWasCreated
  _implicitRules?: unknown
  language?: LanguageOfTheResourceContent
  _language?: unknown
  meta?: unknown
  contained?: ContainedInlineResources
  extension?: AdditionalContentDefinedByImplementations
  modifierExtension?: ExtensionsThatCannotBeIgnored
  text?: unknown
  active?: WhetherThisPractitionerSRecordIsInActiveUse
  _active?: unknown
  address?: AddressEsOfThePractitionerThatAreNotRoleSpecificTypicallyHomeAddress
  birthDate?: TheDateOnWhichThePractitionerWasBorn
  _birthDate?: unknown
  communication?: ALanguageWhichMayBeUsedToCommunicateWithThePractitioner
  deceasedBoolean?: IndicatesIfThePractitionerIsDeceasedOrNot
  _deceasedBoolean?: unknown
  deceasedDateTime?: IndicatesIfThePractitionerIsDeceasedOrNot1
  _deceasedDateTime?: unknown
  gender?: MaleFemaleOtherUnknown
  _gender?: unknown
  identifier?: AnIdentifierForThePersonAsThisAgent
  name?: TheNameSAssociatedWithThePractitioner
  photo?: ImageOfThePerson
  qualification?: QualificationsCertificationsAccreditationsLicensesTrainingEtcPertainingToTheProvisionOfCare
  telecom?: AContactDetailForThePractitionerThatApplyToAllRoles
}
