import logging
from django.conf import settings
from django.shortcuts import render

logger = logging.getLogger(__name__)

def landing(request, path: str | None = None):
    context = {
        "title": "National Provider Directory"
    }

    if settings.DEBUG:
        return render(request, "landing.html", context)

    # FIXME: (@abachman-dsac) in production mode, serve the static index.html
    # file generated by vite
    return render(request, "index.html", context)
